### ISSUE TITLE
Request: please allow it to generate the needed code for custom views : "onSaveInstanceState" and "onRestoreInstanceState"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mcharmas/android-parcelable-intellij-plugin#37]
As the title says.

Suppose you create a class that extends from some View (like TextView or ImageView), please let us generate the code needed for it, and choose which fields to store and restore.

**Comment by DariusL** [comment]
This feature is out of scope for this library. I haven't tried this myself, but [Icepick](https://github.com/frankiesardo/icepick) seems to have this exact feature.

**Comment by AndroidDeveloperLB** [comment]
too bad. thanks anyway.
