### ISSUE TITLE
Checkstyle issue

### ISSUE THREAD

**Issue by mgursch** [mcharmas/android-parcelable-intellij-plugin#38]
Hello

i'm checking my project with checkstyle to find code related issues. It is warning me about this

public static final Parcelable.Creator<ComplaintData> CREATOR = new Parcelable.Creator<ComplaintData>() {
        public ComplaintData createFromParcel( Parcel source ) {return new ComplaintData(source);}
        public ComplaintData[] newArray( int size ) {return new ComplaintData[size];}
    };

with the following messages:

'return' is not preceded with whitespace.
'{' is not followed by whitespace.
';' is not followed by whitespace.
'}' is not preceded with whitespace.

Is it possible to fix this issues in the plugin ? 

Thanks a lot

**Comment by mcharmas** [comment]
It's strange. So the code is not formatted at all? IntelliJ should autoformat the code to match style after generation. What checkstyle and intelliJ version are you using?

**Comment by mgursch** [comment]
Hi

ok i found a way to format this with intellj - sorry for the opened issue

thanks for your help

**Comment by mcharmas** [comment]
No problem.
