### ISSUE TITLE
Should describeContents return hashCode instead of 0?

### ISSUE THREAD

**Issue by octohub** [mcharmas/android-parcelable-intellij-plugin#40]
Hello all,

I am sure there is a reason for this, but `describeContents` returns `0`, why not return `hashCode()` instead?

Neither implementation is that helpful, but I would say `hashCode()` is better than `0`.

What do you guys think?

**Comment by mcharmas** [comment]
Hi,
describeContents is a bit of mystery. Here is some explanation: http://stackoverflow.com/questions/4076946/parcelable-where-when-is-describecontents-used

For more details you probably would have to dive deep into Android sources. Deducing from SO response and enigmatic docs 0 value is a safe default.

**Comment by octohub** [comment]
@mcharmas Really appreciate the prompt response, thank you. Love the plugin, awesome work!
