### ISSUE TITLE
Add SuppressWarning annotation for non-param constructor

### ISSUE THREAD

**Issue by Muyangmin** [mcharmas/android-parcelable-intellij-plugin#45]
Thank you very much for this nice plugin! 
In my opinion,  the non param constructor for the generated class is necessary but the compiler maybe not able to detect this, so could we add **SuppressWarning("unused")** for the constructor?  Thanks again for reading this issue.

**Comment by DariusL** [comment]
AFAIK, the default ctor is generated in case you use it to instantiate the class. I don't think it should be generated at all.

**Comment by Muyangmin** [comment]
Thanks for your reply, now I got it.
